(defpackage #:cl-resilience-kit/test
  (:use #:cl)
  (:shadowing-import-from #:cl-weave #:describe)
  (:import-from #:cl-weave
                #:around-each
                #:expect
                #:finishes
                #:gen-integer
                #:gen-list
                #:gen-member
                #:it
                #:it-concurrent
                #:it-each
                #:it-property
                #:signals
                #:results-status
                #:root-suite
                #:run
                #:with-continuation-result
                #:with-continuation-values)
  (:import-from #:cl-concurrent-kit
                #:current-thread
                #:join-thread
                #:make-semaphore
                #:make-thread
                #:signal-semaphore
                #:wait-on-semaphore)
  (:import-from #:cl-resilience-kit
                #:attempt-timeout
                #:attempt-timeout-timeout
                #:bulkhead-call
                #:bulkhead-in-flight
                #:bulkhead-limit
                #:bulkhead-rejected
                #:bulkhead-rejected-in-flight
                #:call-with-hedging
                #:call-with-deadline
                #:call-with-request-coalescing
                #:call-with-resilience
                #:call-with-resilience/k
                #:call-with-retry
                #:cancel-cancellation-token
                #:cancellation-token-cancelled-p
                #:circuit-breaker-active-probes
                #:circuit-breaker-call
                #:circuit-breaker-failure-count
                #:circuit-breaker-generation
                #:circuit-breaker-opened-at
                #:circuit-open
                #:circuit-breaker-reset
                #:circuit-breaker-state
                #:compute-backoff-delay
                #:current-deadline
                #:deadline-exceeded
                #:deadline-exceeded-attempt
                #:deadline-exceeded-p
                #:deadline-exceeded-stage
                #:deadline-remaining
                #:deadline-exceeded-observed-at
                #:idempotency-conflict
                #:make-bulkhead
                #:make-cancellation-token
                #:make-circuit-breaker
                #:make-resilience-event
                #:make-resilience-executor
                #:make-rate-limiter
                #:make-request-coalescer
                #:make-retry-budget
                #:make-retry-decision
                #:make-retry-policy
                #:rate-limit-exceeded
                #:rate-limit-exceeded-retry-after
                #:rate-limiter-acquire
                #:rate-limiter-tokens
                #:resilience-cancelled
                #:resilience-cancelled-reason
                #:resilience-error
                #:resilience-execution-timeout
                #:resilience-execution-timeout-backend
                #:resilience-execution-timeout-timeout
                #:resilience-event-operation
                #:resilience-event-p
                #:resilience-event-type
                #:resilience-executor-call
                #:resilience-executor-shutdown
                #:resilience-hard-timeout
                #:resilience-hard-timeout-backend
                #:retry-budget-acquire
                #:retry-budget-remaining
                #:retry-budget-used
                #:retry-classifier-error
                #:retry-classifier-error-cause
                #:retry-exhausted
                #:retry-exhausted-attempts
                #:retry-exhausted-last-condition
                #:retry-exhausted-last-result
                #:retry-exhausted-reason
                #:retry-policy-should-retry-p
                #:request-coalescer-size
                #:with-deadline
                #:with-resilience-event-handler
                #:with-retry
                #:with-rate-limiter)
  (:export #:run-tests))

(in-package #:cl-resilience-kit/test)
