(defpackage #:resilience-kit
  (:nicknames #:cl-resilience-kit)
  (:use #:cl)
  (:import-from #:cl-boundary-kit
                #:clock-monotonic
                #:make-clock
                #:make-random-source
                #:make-sleeper
                #:random-source-random
                #:sleeper-sleep)
  (:import-from #:cl-date-kit
                #:duration-of-seconds)
  (:import-from #:cl-concurrent-kit
                #:condition-broadcast
                #:condition-notify
                #:condition-wait
                #:deliver
                #:deliver-error
                #:executor-high-water-mark
                #:executor-queue-capacity
                #:executor-queue-depth
                #:executor-shutdown-p
                #:executor-terminated-p
                #:future
                #:await
                #:make-condition-variable
                #:make-executor
                #:make-lock
                #:make-promise
                #:operation-timed-out
                #:operation-timed-out-operation
                #:promise-all-failed
                #:promise-all-failed-causes
                #:promise-any
                #:promise-already-fulfilled
                #:shutdown-executor
                #:try-submit
                #:with-timeout
                #:with-lock-held)
  (:export
   ;; Cooperative cancellation.
   #:cancellation-token
   #:make-cancellation-token
   #:cancellation-token-parent
   #:cancellation-token-cancelled-p
   #:cancellation-token-reason
   #:cancel-cancellation-token
   #:check-cancellation-token

   ;; Structured events.
   #:resilience-event
   #:resilience-event-p
   #:make-resilience-event
   #:resilience-event-type
   #:resilience-event-operation
   #:resilience-event-attempt
   #:resilience-event-stage
   #:resilience-event-condition
   #:resilience-event-result
   #:resilience-event-delay
   #:resilience-event-reason
   #:resilience-event-timestamp
   #:resilience-event-context
   #:resilience-event-metadata
   #:resilience-event-duration

   ;; Propagated operation context and observation.
   #:resilience-context
   #:make-resilience-context
   #:resilience-context-operation
   #:resilience-context-correlation-id
   #:resilience-context-trace-id
   #:resilience-context-span-id
   #:resilience-context-parent-span-id
   #:resilience-context-idempotency-key
   #:resilience-context-tags
   #:resilience-context-baggage
   #:current-resilience-context
   #:merge-resilience-context
   #:with-resilience-context
   #:with-resilience-event-handler
   #:resilience-metrics
   #:make-resilience-metrics
   #:record-resilience-event
   #:resilience-metrics-total-events
   #:resilience-metrics-count
   #:resilience-metrics-duration
   #:resilience-metrics-snapshot
   #:reset-resilience-metrics
   #:resilience-metrics-handler
   #:resilience-observer
   #:make-resilience-observer
   #:resilience-observer-handlers
   #:resilience-observer-handler
   #:resilience-observer-warning
   #:resilience-observer-warning-phase
   #:resilience-observer-warning-handler
   #:resilience-observer-warning-event
   #:resilience-observer-warning-cause

   ;; Distributed state and fencing leases.
   #:resilience-state-store
   #:memory-state-store
   #:make-memory-state-store
   #:state-store-get
   #:state-store-put-if-version
   #:state-store-delete-if-version
   #:state-store-scan-prefix
   #:resilience-lease-store
   #:memory-lease-store
   #:make-memory-lease-store
   #:resilience-lease
   #:resilience-lease-key
   #:resilience-lease-owner
   #:resilience-lease-fencing-token
   #:resilience-lease-expires-at
   #:resilience-lease-ttl
   #:acquire-resilience-lease
   #:renew-resilience-lease
   #:release-resilience-lease
   #:resilience-lease-held-p
   #:with-resilience-lease

   ;; Process lifecycle and health.
   #:resilience-lifecycle
   #:make-resilience-lifecycle
   #:resilience-lifecycle-state
   #:resilience-lifecycle-active
   #:resilience-lifecycle-accepting-p
   #:begin-resilience-drain
   #:enter-resilience-lifecycle
   #:leave-resilience-lifecycle
   #:await-resilience-drained
   #:stop-resilience-lifecycle
   #:with-resilience-lifecycle
   #:health-registry
   #:make-health-registry
   #:register-health-check
   #:unregister-health-check
   #:health-report
   #:health-ready-p
   #:health-live-p

   ;; Deadline context.
   #:with-deadline
   #:call-with-deadline
   #:current-deadline
   #:deadline-remaining
   #:deadline-exceeded-p

   ;; Retry policy and execution.
   #:retry-decision
   #:make-retry-decision
   #:retry-decision-retry-p
   #:retry-decision-delay-hint
   #:retry-decision-reason
   #:retry-policy
   #:make-retry-policy
   #:retry-policy-max-attempts
   #:retry-policy-initial-delay
   #:retry-policy-multiplier
   #:retry-policy-max-delay
   #:retry-policy-jitter
   #:retry-policy-retry-safe-p
   #:retry-policy-condition-classifier
   #:retry-policy-result-classifier
   #:retry-policy-random-source
   #:retry-policy-should-retry-p
   #:compute-backoff-delay
   #:retry-budget
   #:make-retry-budget
   #:retry-budget-limit
   #:retry-budget-window
   #:retry-budget-used
   #:retry-budget-remaining
   #:retry-budget-acquire
   #:distributed-retry-budget
   #:make-distributed-retry-budget
   #:distributed-retry-budget-store
   #:distributed-retry-budget-key
   #:call-with-retry
   #:with-retry

   ;; Circuit breaker.
   #:circuit-breaker
   #:make-circuit-breaker
   #:circuit-breaker-call
   #:circuit-breaker-state
   #:circuit-breaker-failure-threshold
   #:circuit-breaker-reset-timeout
   #:circuit-breaker-success-threshold
   #:circuit-breaker-condition-classifier
   #:circuit-breaker-result-classifier
   #:circuit-breaker-clock
   #:circuit-breaker-monotonic-units-per-second
   #:circuit-breaker-failure-count
   #:circuit-breaker-opened-at
   #:circuit-breaker-active-probes
   #:circuit-breaker-half-open-probe-limit
   #:circuit-breaker-generation
   #:circuit-breaker-reset
   #:with-circuit-breaker

   ;; Distributed circuit breaker.
   #:distributed-circuit-breaker
   #:make-distributed-circuit-breaker
   #:distributed-circuit-breaker-call
   #:distributed-circuit-breaker-failure-threshold
   #:distributed-circuit-breaker-reset-timeout
   #:distributed-circuit-breaker-half-open-probe-limit
   #:distributed-circuit-breaker-success-threshold
   #:distributed-circuit-breaker-condition-classifier
   #:distributed-circuit-breaker-result-classifier
   #:distributed-circuit-breaker-clock
   #:distributed-circuit-breaker-monotonic-units-per-second
   #:distributed-circuit-breaker-store
   #:distributed-circuit-breaker-key
   #:distributed-circuit-breaker-lease-store
   #:distributed-circuit-breaker-lease-owner
   #:distributed-circuit-breaker-lease-ttl
   #:distributed-circuit-breaker-state
   #:distributed-circuit-breaker-failure-count
   #:distributed-circuit-breaker-opened-at
   #:distributed-circuit-breaker-active-probes
   #:distributed-circuit-breaker-generation
   #:distributed-circuit-breaker-reset
   #:with-distributed-circuit-breaker

   ;; Bulkhead.
   #:bulkhead
   #:make-bulkhead
   #:bulkhead-call
   #:bulkhead-limit
   #:bulkhead-in-flight
   #:with-bulkhead
   #:queued-bulkhead
   #:make-queued-bulkhead
   #:queued-bulkhead-max-queue
   #:queued-bulkhead-queue-size
   #:queued-bulkhead-call
   #:with-queued-bulkhead

   ;; Rate limiter.
   #:rate-limiter
   #:make-rate-limiter
   #:rate-limiter-acquire
   #:rate-limiter-capacity
   #:rate-limiter-refill-rate
   #:rate-limiter-clock
   #:rate-limiter-monotonic-units-per-second
   #:rate-limiter-sleeper
   #:rate-limiter-tokens
   #:rate-limiter-last-refill
   #:with-rate-limiter

   ;; Composition.
   #:resilience-executor
   #:make-resilience-executor
   #:resilience-executor-queue-depth
   #:resilience-executor-queue-capacity
   #:resilience-executor-high-water-mark
   #:resilience-executor-shutdown-p
   #:resilience-executor-terminated-p
   #:resilience-executor-try-submit
   #:resilience-executor-submit
   #:resilience-executor-call
   #:with-resilience-executor
   #:resilience-executor-shutdown
   #:call-with-hedging
   #:with-hedging
   #:request-coalescer
   #:make-request-coalescer
   #:request-coalescer-size
   #:call-with-request-coalescing
   #:with-request-coalescing
   #:call-with-resilience/k
   #:with-resilience/k
   #:call-with-resilience
   #:with-resilience

   ;; Structured errors.
   #:resilience-error
   #:resilience-error-operation
   #:resilience-error-message
   #:retry-exhausted
   #:retry-exhausted-attempts
   #:retry-exhausted-last-condition
   #:retry-exhausted-last-result
   #:retry-exhausted-reason
   #:retry-exhausted-policy
   #:retry-classifier-error
   #:retry-classifier-error-cause
   #:deadline-exceeded
   #:deadline-exceeded-deadline
   #:deadline-exceeded-observed-at
   #:deadline-exceeded-stage
   #:deadline-exceeded-attempt
   #:attempt-timeout
   #:attempt-timeout-timeout
   #:circuit-open
   #:circuit-open-state
   #:circuit-open-retry-at
   #:circuit-open-generation
   #:bulkhead-rejected
   #:bulkhead-rejected-limit
   #:bulkhead-rejected-in-flight
   #:rate-limit-exceeded
   #:rate-limit-exceeded-requested-tokens
   #:rate-limit-exceeded-available-tokens
   #:rate-limit-exceeded-retry-after
   #:resilience-cancelled
   #:resilience-cancelled-token
   #:resilience-cancelled-reason
   #:resilience-store-error
   #:resilience-store-error-key
   #:resilience-store-error-cause
   #:resilience-store-conflict
   #:resilience-store-conflict-expected-version
   #:resilience-store-conflict-actual-version
   #:resilience-lease-unavailable
   #:resilience-lease-unavailable-key
   #:resilience-lease-unavailable-owner
   #:resilience-lease-unavailable-retry-after
   #:resilience-lease-lost
   #:resilience-lease-lost-key
   #:resilience-lease-lost-owner
   #:resilience-lease-lost-fencing-token
   #:stale-fencing-token
   #:stale-fencing-token-key
   #:stale-fencing-token-fencing-token
   #:stale-fencing-token-current-fencing-token
   #:resilience-draining
   #:resilience-draining-state
   #:resilience-execution-rejected
   #:resilience-execution-rejected-reason
   #:resilience-execution-rejected-queue-size
   #:resilience-execution-timeout
   #:resilience-execution-timeout-timeout
   #:resilience-execution-timeout-backend
   #:resilience-hard-timeout
   #:resilience-hard-timeout-backend
   #:hedge-unsafe
   #:hedge-unsafe-reason
   #:hedge-exhausted
   #:hedge-exhausted-causes
   #:hedge-exhausted-attempts
   #:idempotency-key-required
   #:idempotency-conflict
   #:idempotency-conflict-key
   #:idempotency-conflict-existing-value))
